HeadspaceMeditation/beyonce

README.md
package.json
src/main/codegen/generateModelInterface.ts
src/test/codegen/generateModels.test.ts

This PR improves Beyoncé's import syntax used to reference external (imported) types from the YAML file. 
Previously, it `address: main/Address` would expand into `import { Address } from main/Address`. This wouldn't work if the file name was different than the type name. 
So now you can do `address: Address from @maps/address`, which works with almost everything.

[Beyoncé]: Add better import syntax

---

jest.config.js
package-lock.json
package.json
src/main/codegen/generateGSIs.ts
src/main/codegen/generateModels.ts
src/main/codegen/types.ts
src/test/codegen/generateModels.test.ts

This PR extends GSI support in Beyoncé to allow referencing the (base) table's partition and sort keys.  This is useful as it's a common use-case to want to "swap" these keys in a GSI - i.e. GSI pk = Table sk, GSI sk = Table pk.

[Beyoncé]: Allow GSIs to use pk and sk as fields

---

package.json
src/main/codegen/generateModelHelpers.ts
src/main/codegen/generateModels.ts
src/main/codegen/generateTaggedUnion.ts
src/main/dynamo/Beyonce.ts
src/main/dynamo/Key.ts
src/main/dynamo/Model.ts
src/main/dynamo/QueryBuilder.ts
src/main/dynamo/util.ts
src/main/index.ts
src/test/codegen/generateModels.test.ts

This PR updates Beyonce's `Model` type to be a tagged union of all the specified models. So
`interface Model { name: string }` becomes `type Model = Author | Book` . This makes it easy to "pattern match" in downstream code.

Make "Model" type a union of all specified models

---

README.md
package.json
src/main/codegen/generateGSIs.ts
src/main/dynamo/Beyonce.ts
src/main/dynamo/GSI.ts
src/main/dynamo/JayZConfig.ts
src/main/dynamo/util.ts
src/test/codegen/generateCode.test.ts
src/test/dynamo/models.ts
src/test/dynamo/util.ts

Previously when enabling JayZ encryption w/ Beyonce you had to explicitly pass a set of fields to avoid encrypting. 
But now the (generated) `Table` class is aware of which fields to avoid encrypting (because it knows the partition/sort keys for the table + gsis on the table). So there's no need to do that. 
This PR cleans this up.

[Beyonce]: Cleanup JayZ Config

---

README.md
package.json
src/main/dynamo/Beyonce.ts
src/main/dynamo/Model.ts
src/main/dynamo/QueryBuilder.ts
src/main/dynamo/keys.ts
src/test/dynamo/Beyonce.test.ts
src/test/dynamo/ExpressionBuilder.test.ts

This PR adds functionality to `.query` and retrieve a single type of model (e.g. give me all books for author 123).  
To reduce the amount of data processed by DynamoDB when making this type of query, we also now automatically apply a `KeyConditionExpression` that enforces that the table's sortKey begins with the specified model's prefix (e.g. `begins_with(..., Book)`).

[Beyonce]: Support querying for single type of model 

---

README.md
package.json
src/main/dynamo/QueryBuilder.ts
src/test/dynamo/Beyonce.test.ts

This PR adds the ability to manually step through pages of a query result, which is useful if you want to throttle reads and/or send paginated results + a cursor down to a client.

[Beyoncé]: Add pagination support

---

package.json
src/main/dynamo/Beyonce.ts
src/main/dynamo/GSI.ts
src/main/dynamo/Model.ts
src/main/dynamo/Partition.ts
src/main/dynamo/QueryBuilder.ts
src/main/dynamo/groupModelsByType.ts
src/main/dynamo/keys.ts
src/test/dynamo/Beyonce.test.ts

This PR adjusts `.query` and `.batchGet` to return empty arrays for model types that could potentially be returned from the db. Previously if no models of that type were found, the model type key would come back as undefined. 
Fixes #24

[Beyonce]: Return empty lists when items not found in Query / BatchGet

---

package.json
src/main/dynamo/Beyonce.ts
src/main/dynamo/QueryBuilder.ts
src/test/dynamo/Beyonce.test.ts

This PR adds a `consistentRead` option to `get` and `batchGet` operations on the Beyonce class.

[Beyonce]: Enable consistent reads

---

README.md
package.json
src/main/dynamo/Beyonce.ts
src/main/dynamo/QueryBuilder.ts
src/main/dynamo/expressions/Attributes.ts
src/main/dynamo/expressions/DynamoDBExpression.ts
src/main/dynamo/expressions/QueryExpressionBuilder.ts
src/main/dynamo/expressions/UpdateItemExpressionBuilder.ts
src/main/dynamo/expressions/Variables.ts
src/main/dynamo/updateItemProxy.ts
src/test/dynamo/Beyonce.test.ts
src/test/dynamo/expressions/QueryExpressionBuilder.test.ts
src/test/dynamo/models.ts

This PR adds functionality to support partial updates of Dynamo items. For context, here are the new docs:
Beyoncé supports type-safe partial updates on items, without having to read the item from the db first. And it works, even through nested attributes:
```TypeScript
const updatedAuthor = await beyonce.update(AuthorModel.key({ id: "1" }), (author) => {
author.name = "Jack London",
author.details.description = "American novelist"
delete author.details.someDeprecatedField
})
```
Here `author` is an intelligent proxy object (thus we avoid having to read the full item from the DB prior to updating it).And `beyonce.update(...)` returns the full `Author`, with the updated fields
Fixes: #27 and #25

[Beyonce]: Support partial updates

---

src/test/codegen/generateCode.test.ts

I think there may be an issue with the encryptionBlacklist not grabbing all the keys in the compound key. Adding this test from my other PR.

Add test for compound key model generation

---

README.md
package.json
src/main/codegen/generateModels.ts
src/main/codegen/generateTables.ts
src/main/codegen/types.ts
src/main/codegen/util.ts
src/main/dynamo/Model.ts
src/test/codegen/generateCode.test.ts
src/test/dynamo/Beyonce.test.ts
src/test/dynamo/models.ts

@cjoelrun  started this work during our last hackday in: https://github.com/ginger-io/beyonce/pull/33. This PR splits off an incremental chunk of that work so we can merge a useful feature in. 
Previously, Beyonce would force you to structure your partition / sort keys as a tuple-2 composed of [prefix, modelFieldName]. But there are many use-cases in Dynamo where you'd want to have a "compound" key -- i.e. a key formed from not 1, but multiple fields on the model. 
As an example, we might have: 
1. A model for `SalesRep`, where our pk is `["SalesRep", "$id"]`.
2. An `Sale` model that has the same partition key as the rep it's attached to and a sort key that's like `[Sale, "$country", "$state", "$city"]`. 
The compound key in 2) would allow us to query for all sales by a rep in a given …

[Beyonce]: Allow Compound Partition/Sort Keys

---

README.md
package.json
src/main/dynamo/Beyonce.ts
src/main/dynamo/ScanBuilder.ts
src/test/dynamo/query.test.ts
src/test/dynamo/scan.test.ts
src/test/dynamo/util.ts

This PR builds off of #42  and adds parallel scan functionality, so users can break their table into N segments and scan each in parallel. 
```TypeScript
// Somewhere inside of Worker 1
const segment1 = beyonce
.scan({ parallel: { segmentId: 0, totalSegments: 2 }})
.iterator()
for await (const results of segment1) {
// ...
}
// Somewhere inside of Worker 2
const segment2 = beyonce
.scan({ parallel: { segmentId: 1, totalSegments: 2 }})
.iterator()
for await (const results of segment2) {
// ...
}
```

[Beyonce]: Add support for parallel scans

---

package.json
src/main/dynamo/QueryBuilder.ts
src/main/dynamo/ScanBuilder.ts
src/main/dynamo/expressions/Attributes.ts
src/main/dynamo/expressions/QueryExpressionBuilder.ts
src/main/dynamo/expressions/UpdateItemExpressionBuilder.ts
src/main/dynamo/expressions/Variables.ts
src/test/dynamo/expressions/QueryExpressionBuilder.test.ts
src/test/dynamo/query.test.ts

This PR fixes a bug that @cjoelrun encountered where if you had a query that used an attribute name multiple times with different values, like: 
```TypeScript
beyonce
.query(...)
.where("model", "=", Model.Foo)
.or("model", "=", Model.Boo)
```
Then only the last value provided would be used. 
The root cause was we were using the attribute's name as the key in the [ExpressionAttributeValues](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ExpressionAttributeValues.html) map passed to DynamoDB. And as a result, it was always last write wins. 
This PR fixes that bug by using an auto-incrementing values map, e.g. `:v1` => `Model.foo`, `:v2` => `Model.boo`.

[Beyonce]: Fix a bug where you couldn't use the same attribute name multiple times in queries

---

Dockerfile
README.md
package.json
src/main/codegen/generateCode.ts
src/main/codegen/generateGSIs.ts
src/main/codegen/types.ts
src/test/codegen/generateCode.test.ts

This PR restructures the format of Beyonce's YAML configuration file. Now, we separate the definition of model fields (i.e. just the data) from their partition and sort key definitions (i.e. how we stuff them into Dynamo).
This is also closer to an end goal where we'd be able to define model fields as TypeScript interfaces and the partition/sort keys as external configuration.

[Beyonce]: Rework structure of YAML file

---

package.json
src/test/dynamo/Beyonce.test.ts
src/test/dynamo/models.ts
yarn.lock

This PR prevents errors from occurring in Beyonce if you:
1. You have JayZ (encryption library) enabled
2. You attempt to save a model to Dynamo that has a k/v pair where the key is present but the value is `undefined`
3. You attempt to read that model back
This is a bug that was fixed in: https://github.com/ginger-io/jay-z/pull/10. So this PR just pulls in the latest JayZ library + adds unit tests to ensure it works within the context of Beyonce/Dynamo as expected.

[Beyonce]: Don't fail if model field is set to undefined when JayZ is enabled

---

README.md
package.json
src/main/dynamo/ScanBuilder.ts
src/main/dynamo/pagedIterator.ts
src/test/dynamo/query.test.ts
src/test/dynamo/scan.test.ts
src/test/dynamo/util.ts

Previously, if you attempted a `Query` or `Scan` operation using a paged iterator and you hit an error, the iterator would give up and terminate itself. Now, we yield control to the caller by handing them an `errors` array so they can decide wether or not they'd like to proceed with their operation, or give up. 
One place where this is useful is if you're performing a full table scan, and you don't want a bad record or two to stop your scan cold.

[Beyonce]: Better error handling for paged iterators

---

README.md
package.json
src/main/CompositeError.ts
src/main/dynamo/Beyonce.ts
src/main/dynamo/QueryBuilder.ts
src/main/dynamo/ScanBuilder.ts
src/main/dynamo/pagedIterator.ts
src/main/dynamo/util.ts
src/test/dynamo/scan.test.ts
src/test/dynamo/util.ts
yarn.lock

https://github.com/ginger-io/beyonce/pull/50 added support to allow callers who invoked `Query` and `Scan` operations to continue processing if a loading particular iterator page generated an error. 
But if encryption was enabled via our JayZ library, one bad record would result in giving up on the entire page of records. This PR fixes that.
Now, if we encounter one or more bad records within an iterator page, we'll process as many as we can + return errors for the rest.

[Beyonce]: Allow partial success when decrypting items within an iterator page

---

src/main/dynamo/Beyonce.ts
src/main/dynamo/QueryBuilder.ts
src/main/dynamo/ScanBuilder.ts
src/main/dynamo/expressions/QueryExpressionBuilder.ts
src/test/dynamo/Beyonce.test.ts
src/test/dynamo/query.test.ts
src/test/dynamo/scan.test.ts
src/test/dynamo/util.ts

This PR fixes a bug where if you: 
1. Called `scan` or `query` 
2. Added filtering via `where(...)`
3. Called the `iterator()` method (instead of `exec`)
Your first page of results would have the filter applied, but subsequent ones would not.

[Beyonce]: Fix a bug where pagedIterators would "forget" their filters after processing the 1st page

---

package.json
src/main/dynamo/QueryBuilder.ts
src/main/dynamo/ScanBuilder.ts
src/main/dynamo/iterators/pagedIterator.ts
src/main/dynamo/iterators/types.ts
src/main/dynamo/iterators/util.ts
src/test/dynamo/iterators/util.test.ts

This PR makes `Cursor` values returned by scan/query iterators opaque to the caller by base64 encoding them. 
This is nice from an API pov as it does not leak implementation details about what the cursor is (which is the DynamoDB last evaluated key). And, it also makes cursor values more compact for easier copy/pasting when you want to resume a query/scan from a particular iterator page.

[Beyonce] Make Cursor values opaque to the caller

---

README.md
src/main/dynamo/Beyonce.ts
src/main/dynamo/QueryBuilder.ts
src/main/dynamo/ScanBuilder.ts
src/test/dynamo/Beyonce.test.ts
src/test/dynamo/query.test.ts
src/test/dynamo/util.ts

This PR adds a new `executeTransaction` method that allows callers to put and delete a set of records within the same transaction. We had a narrower method, `batchPutWithTransaction` which is now redundant and is thus marked as deprecated and will soon be removed. 
DynamoDB supports a wider range of transaction operations (e.g. conditions on the transaction and updating records), so we'll want to extend `executeTransaction` to handle these use cases as well.  But that is left to future PRs.
I snuck in a few small changes as separate commits -- fixing a test, and swapping several `type` definitions to `interfaces` (which allows for using the `extends` keyword). 
**How to review?**
Commit-by-commit

[Beyonce]: Add executeTransaction method / deprecate batchPutWithTransaction

---

.vscode/settings.json
package.json
src/main/dynamo/iterators/pagedIterator.ts
src/test/dynamo/query.test.ts

This PR fixes a bug with our paginated `query`/`scan` operators where the final iterator results page wasn't returning `undefined` for the `cursor` (which is a signal to the user that we're "all done"). Instead, we were returning a copy of the n-1 cursor.

fix: [Beyonce] make returned cursor undefined when we hit final iterator page

---

README.md
package.json
src/main/dynamo/Beyonce.ts
src/test/dynamo/Beyonce.test.ts
src/test/dynamo/models.ts
src/test/dynamo/query.test.ts
src/test/dynamo/util.ts

This PR is a superset of https://github.com/ginger-io/beyonce/pull/48, it contains its changes + additional changes. 
https://github.com/ginger-io/beyonce/pull/48 added a new `batchPut` method. But, given we recently added support for a `executeTransaction` method that allows for N put/delete operations -- it'd be more consistent to offer `batchWrite` and `batchWriteWithTransaction` methods.
So, that's what this PR does. 
`batchWrite` and `batchWriteWithTransaction` have different error-handling semantics, `batchWrite` may (or may not) return a list of failed put and delete operations that the caller can retry. This particular codepath needs unit tests, but we currently don't have an easy way to trigger "unprocessed item errors" in Dynamo (yet) -- so we'll add that …

feat: Add batchWrite method

---

README.md
package.json
src/main/dynamo/Beyonce.ts
src/test/dynamo/Beyonce.test.ts

This PR makes a change to `batchGet` to automatically split DynamoDB calls into N concurrent requests, _if_ the caller asks for more than 100 keys at once. 
Dynamo supports retrieving a max of 100 keys at a time. So, this should make things easier on consumers. Now they can ask for more than 100 items without having to do the request splitting themselves. 
Some future work here would be to allow partial success of batchGets. Right now we'll throw an error if any one of the concurrent requests fails.

feat: Automatically split large batchGet calls into concurrent requests

---

src/main/dynamo/iterators/pagedIterator.ts
src/test/dynamo/models.ts
src/test/dynamo/query.test.ts
src/test/dynamo/util.ts

This PR fixes a bug where `pagedIterator` was doing something dumb (my fault). It was performing a side-effecting async `.map` on an array, which has two problems: 
1. Maps shouldn't perform side-effects
2. The side-effect it was performing was to push items onto a results array. 
2# above is particularly problematic as these Promises can resolve out of order, which meant that in some cases results would be returned out of order (relative to their sort key).

fix: Ensure pagedIterator preserves ordering of results when promises resolve out of order

---

package.json
src/main/dynamo/operations/transactWriteItems.ts

**What's in this PR**
When Dynamo throws a transaction cancelled exception, its HTTP response body includes a list of reasons for cancellation. But the error thrown from the sdk's Promise object does not include these reasons. 
So, per: https://github.com/aws/aws-sdk-js/issues/2464#issuecomment-503524701 -- we have to parse them out.

fix: When Dynamo throws a transaction cancelled exception, include the reasons for cancellation

---

README.md
package.json
src/main/dynamo/Beyonce.ts
src/main/dynamo/operations/transactWriteItems.ts
yarn.lock

This PR adds a `clientRequestToken` option to `batchWriteWithTransaction`. Passing this forces transactions to be idempotent [per the docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transaction-apis.html#transaction-apis-txwriteitems-idempotency). 
So passing this should avoid "transaction cancelled errors" if simultaneous requests with the same content + `clientRequestToken` are submitted.

feat: Add clientRequestToken option to batchWriteWithTransaction

---

src/main/dynamo/Beyonce.ts
src/main/dynamo/operations/transactWriteItems.ts
src/test/dynamo/Beyonce.test.ts

Asana ticket: https://app.asana.com/0/1201082158239874/1202662582963198
This PR updates Beyonce to support checking for uniqueness when executing a `batchWriteWithTransaction` PUT. For example:
```
db.batchWriteWithTransaction({
putItems: [
{ ...item, failIfNotUnique: true }
]
})
```
If there were already a record in DynamoDB with the same pk and sk (if applicable), the above would raise a "ConditionalCheckFailed" error since we set `failIfNotUnique: true`.
Related PR: https://github.com/ginger-io/ginger-vault-service/pull/645

feat: support uniqueness check on PUT

---

Dockerfile
codeship-services.yml

https://headspace.atlassian.net/browse/CARE-4677
Tests were failing in CI due to not pinning the version of `amazon/dynamodb-local`.
Note that SonarCloud flagged this because of running the Dockerfile as root. Based on the risk assessment that SonarCloud provides, it is _not_ a vulnerability in our use case since we do not use this Dockerfile for running a service in prod; we use it only for running tests.

fix: [CARE-4677] tests failed due to unmocked AWS calls
